[package]
name = "pump19-rs"
version = "0.1.0"
repository = "https://github.com/pump19/pump19-rs"
authors = ["Kevin Perry"]
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
dotenv = "0.15.0"
futures = "0.3.5"
irc = "0.14.0"
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_regex = "1.1.0"
reqwest = { version = "0.10.6", features = ["json"] }
sqlx = { version = "0.3.5", default-features = false, features = [
    "runtime-tokio",
    "macros",
    "postgres",
] }
tokio = "0.2.21"
xdg = "2.2.0"
