[package]
name = "pump19-rs"
version = "0.1.0"
authors = ["Kevin Perry"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
futures = "0.3.5"
irc = "0.14.0"
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
serde = "1.0.112"
serde_derive = "1.0.112"
tokio = "0.2.21"
tokio-postgres = "0.5.4"
toml = "0.5.6"
xdg = "2.2.0"
