name: Rust

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pg:
        image: postgres:alpine
        env:
          POSTGRES_USER: pump19
          POSTGRES_PASSWORD: pump19

    env:
      DATABASE_URL: "postgresql://pump19:pump19@localhost:5432/pump19"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: target/release/pump19-rs
