name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pg:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: pump19
          POSTGRES_PASSWORD: pump19
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://pump19:pump19@localhost:5432/pump19"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create codefall table
      run: >
        psql -h localhost -U pump19 -d pump19 -a -c
        'CREATE TABLE codefall_unclaimed(
          cid         integer,
          description text,
          code_type   text,
          user_name   text,
          key         character(6)
        );'

    - name: Build release configuration
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: target/release/pump19-rs
